Spring boot security
evgenkolner/BookOnlineService pull request #6
Opened 2023-10-30 12:59 UTC by evgenkolner

2023-10-30 21:06 UTC, viacheslav-torbin requested changes

2023-10-30 21:06 UTC, viacheslav-torbin commented on src/main/java/bookstore/controller/BookController.java
>      @Operation(summary = "Create book", description = "Create book")
Pls provide different summary & description

2023-10-30 21:06 UTC, viacheslav-torbin commented on src/main/java/bookstore/controller/AuthController.java
> +@RequestMapping(value = "/auth")
Endpoinst should be /api/**

2023-10-31 11:34 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/AuthController.java
> +public class AuthController {
I didn't find any Swagger documentation

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/AuthController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
```suggestion
    public UserLoginResponseDto login(@RequestBody @Valid UserLoginRequestDto requestDto) {
```

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/AuthController.java
> +
remove empty line

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
Do we need role USER in some endpoints?

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/user/UserLoginRequestDto.java
> +
remove empty line

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/user/UserRegistrationRequest.java
> +public class UserRegistrationRequest {
Make it record
Also, add @FieldMatch(fields = {"password", "repeatPassword"})

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/user/UserResponseDto.java
> +public class UserResponseDto {
make it record

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/model/User.java
> +        return isDeleted;
```suggestion
        return !isDeleted;
```

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
Add @EntityGraph(attributePaths = "roles")

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Repository annotation is missing

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/AuthenticationService.java
> +    @Autowired
You don't need this annotation here

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/AuthenticationService.java
> +    @Autowired
The same

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/CustomUserDetailsService.java
> +@Component
```suggestion
@Service
```

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RuntimeException("Can't find user by email"));
Too general to throw RuntimeException
You can throw UsernameNotFoundException and remove it from signature of method

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
You can use HttpHeaders.AUTHORIZATION instead of "Authorization"

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Let's make "Bearer " constant

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
the same for 7

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/UserServiceImpl.java
> +@Component
```suggestion
@Service
```

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/UserServiceImpl.java
> +        User savedUser = userRepository.save(user);
Do we need to set Roles?

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.getEmail()).isPresent()) {
you might use exists syntax in JPA repo to avoid calling isPresent

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(255)
Check max size everywhere. It should be the same as in request

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/UserServiceImpl.java
> +        User user = new User();
Let's create method in UserMapper and use it here 
User user = mapper.toUser(request);

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/AuthenticationService.java
> +
remove empty lines

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
You need to handle this exception

2023-10-31 11:34 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/user/UserRegistrationRequest.java
> +public class UserRegistrationRequest {
```suggestion
public class UserRegistrationRequestDto {
```

2023-11-01 10:50 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few mistakes;) Be attentive not all previous comments were fixed ;)

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/AuthController.java
> +public class AuthController {
not fixed

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/AuthController.java
> +@RequestMapping(value = "api/auth")
you can move "/api" to aplication.properties as `server.servlet.context-path`

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/AuthController.java
> +    @PostMapping(value = "/login")
```suggestion
    @PostMapping( "/login")
```

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/dto/user/UserRegistrationRequestDto.java
> +        @Size(min = 6, max = 50)
Why you have different min and max size for registration and login

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/exception/CustomGlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
```suggestion
        return ResponseEntity.status(HttpStatus.CONFLICT)
```

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/model/Role.java
> +@NoArgsConstructor
```suggestion
```
Do you really  need this annotation?

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/service/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
not fixed. Better use existsUserByEmail JPA method

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/test/resources/application.properties
> +jwt.secret=i-am-a-spy-token-give-you-opportunity-to-take-some-information
It’s funny) but it’s a project for your CV so better use a more secure jwt.secret

2023-11-01 10:50 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-roles-table.yaml
> +                    nullable: false
better leave one empty line at the end of each file (check it)

2023-11-01 15:21 UTC, Elena-Bruyako requested changes
Good job! let's fix some comments!

2023-11-01 15:21 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/AuthController.java
> +public class AuthController {
Not fixed

2023-11-01 15:21 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/constraint/FieldMatchValidator.java
> +        if (fieldValue != null) {
You can simplify your code
return fieldValue != null && fieldValue.equals(fieldMatchValue);

2023-11-01 15:21 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(255)
not fixed

2023-11-02 09:33 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-11-02 09:33 UTC, liliia-ponomarenko commented on src/main/java/bookstore/dto/user/UserRegistrationRequestDto.java
> +        @Size(min = 6, max = 60)
```suggestion
        @Size(min = 6, max = 255)
```

2023-11-02 14:25 UTC, merged