Shopping cart model
evgenkolner/BookOnlineService pull request #8
Opened 2023-11-13 08:00 UTC by evgenkolner

2023-11-13 11:08 UTC, teract10s requested changes
Good job. I left some minor comments

2023-11-13 11:08 UTC, teract10s commented on src/main/java/bookstore/controller/ShoppingCartController.java
> +    @PreAuthorize("hasRole('USER')")
is it work without prefix "ROLE_"?

2023-11-13 11:08 UTC, teract10s commented on src/main/java/bookstore/controller/ShoppingCartController.java
> +        User user = (User) authentication.getPrincipal();
Is it controller layer behavior? I had comment from mentors that here would be better to move in service layer

2023-11-13 11:08 UTC, teract10s commented on src/main/java/bookstore/dto/cartitem/CartItemRequestDto.java
> +        @Min(1)
You may also replace it with positive and add null check where it has to be

2023-11-13 11:08 UTC, teract10s commented on src/main/java/bookstore/dto/shoppingcart/ShoppingCartRequestDto.java
> +        int quantity) {
add checks here

2023-11-15 10:09 UTC, Elena-Bruyako requested changes
Good job! let's improve your solution!

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/ShoppingCartController.java
> +                                         @RequestBody CartItemRequestDto requestDto) {
```suggestion
                                         @RequestBody @Valid CartItemRequestDto requestDto) {
```

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/ShoppingCartController.java
> +                                          @RequestBody ShoppingCartRequestDto quantity) {
```suggestion
                                          @RequestBody @Valid ShoppingCartRequestDto quantity) {
```

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/ShoppingCartController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasRole('USER')")
```
It works without ROLE
Check all places

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/cartitem/CartItemRequestDto.java
> +        @Min(1)
Positive is better

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/mapper/CartItemMapper.java
> +
remove empty line

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/mapper/ShoppingCartMapper.java
> +
the same

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/ShoppingCartServiceImpl.java
> +                () -> new RuntimeException("Cannot find shopping cart")));
RuntimeException is too general, please use custom one

2023-11-15 10:09 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/ShoppingCartServiceImpl.java
> +    private ShoppingCart createShoppingCartForUser(User user) {
private methods should be after all public methods

2023-11-17 14:04 UTC, Elena-Bruyako approved these changes
Good job!

2023-11-17 14:26 UTC, merged